spring.application.name=Repifuzz-Assignmnet
#Datasource
spring.datasource.url=jdbc:mysql://localhost:3306/repifuzz_db
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
jwt.secret=verySecretKeyThatIsAtLeast32BytesLongForHS256Algorithm12345
jwt.expirationMs=86400000

